# Generated by Django 4.2.7 on 2023-11-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(choices=[('Информатика', 'Информатика'), ('Математика', 'Математика'), ('Русский язык', 'Русский язык'), ('Английский язык', 'Английский язык'), ('Обществознание', 'Обществознание'), ('География', 'География'), ('Физика', 'Физика'), ('Химия', 'Химия'), ('Биология', 'Биология'), ('Литература', 'Литература'), ('История', 'История'), ('Не задано', 'Не задано')], default='Не задано', max_length=50)),
                ('task_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('task_condition', models.TextField()),
                ('points', models.IntegerField()),
            ],
        ),
    ]
